from flask import jsonify, request, g, make_response
from apis.utils.tokenService import TokenService
from apis.utils.databaseService import DatabaseService
import logging
import pytz
from datetime import datetime
from apis.utils.llmServices import o3_mini_service  # Import the service function

# CONFIGURE LOGGING
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

from apis.utils.config import create_api_response

def o3_mini_route():
    """
    Consumes 3 AI credits per call
    
    O3-Mini LLM model for text generation with variable reasoning effort.

    ---
    tags:
      - LLM
    parameters:
      - name: X-Token
        in: header
        type: string
        required: true
        description: Authentication token
      - name: X-Correlation-ID
        in: header
        type: string
        required: false
        description: Unique identifier for tracking requests across multiple systems
      - name: body
        in: body
        required: true
        schema:
          type: object
          required:
            - user_input
          properties:
            system_prompt:
              type: string
              description: System prompt to control model behavior
              default: "You are a helpful AI assistant"
            user_input:
              type: string
              description: Text for the model to process
            max_completion_tokens:
              type: integer
              minimum: 1
              maximum: 120000
              default: 100000
              description: Maximum number of tokens in the response
            reasoning_effort:
              type: string
              enum: ["high", "medium", "low"]
              default: "medium"
              description: Level of reasoning effort
            json_output:
              type: boolean
              default: false
              description: Whether to return the response in JSON format
            context_id:
              type: string
              description: ID of a context file to use as an enhanced system prompt (optional)
    produces:
      - application/json
    responses:
      200:
        description: Successful model response
        schema:
          type: object
          properties:
            response:
              type: string
              example: "200"
            message:
              type: string
              example: "I'll help you with that question. Based on the information provided..."
            user_id:
              type: string
              example: "user123"
            user_name:
              type: string
              example: "John Doe"
            user_email:
              type: string
              example: "john.doe@example.com"
            model:
              type: string
              example: "o3-mini"
            client_used:
              type: string
              example: "primary"
              description: Which client was used (primary, secondary, tertiary)
            context_used:
              type: string
              example: "ctx_123e4567-e89b-12d3-a456-426614174000"
              description: Context identifier used in this request (or 'none' if no context)
            prompt_tokens:
              type: integer
              example: 125
              description: Number of tokens pass in the prompt
            completion_tokens:
              type: integer
              example: 84
              description: Number of tokens generated by the llm
            total_tokens:
              type: integer
              example: 209
              description: Total number of tokens used
            cached_tokens:
              type: integer
              example: 0
              description: Number of cached tokens (if supported by model)  

      400:
        description: Bad request
        schema:
          type: object
          properties:
            response:
              type: string
              example: "400"
            message:
              type: string
              example: "Missing required fields: user_input"
      401:
        description: Authentication error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Authentication Error"
            message:
              type: string
              example: "Token has expired"
      500:
        description: Server error
        schema:
          type: object
          properties:
            response:
              type: string
              example: "500"
            message:
              type: string
              example: "Internal server error occurred during API request"
    """
    # Get token from X-Token header
    token = request.headers.get('X-Token')
    if not token:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Missing X-Token header"
        }, 401)
    
    # Validate token from database
    token_details = DatabaseService.get_token_details_by_value(token)
    if not token_details:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Invalid token - not found in database"
        }, 401)
    
    # Store token ID and user ID in g for logging and balance check
    g.token_id = token_details["id"]
    g.user_id = token_details["user_id"]  # This is critical for the balance middleware
    
    # Check if token is expired
    now = datetime.now(pytz.UTC)
    expiration_time = token_details["token_expiration_time"]
    
    # Ensure expiration_time is timezone-aware
    if expiration_time.tzinfo is None:
        johannesburg_tz = pytz.timezone('Africa/Johannesburg')
        expiration_time = johannesburg_tz.localize(expiration_time)
        
    if now > expiration_time:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Token has expired"
        }, 401)
    
    # Validate token with Microsoft Graph
    is_valid = TokenService.validate_token(token)
    if not is_valid:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Token is no longer valid with provider"
        }, 401)
        
    # Get user details
    user_id = token_details["user_id"]
    user_details = DatabaseService.get_user_by_id(user_id)
    if not user_details:
        return create_api_response({
            "error": "Authentication Error",
            "message": "User associated with token not found"
        }, 401)
    
    # Get request data
    data = request.get_json()
    if not data:
        return create_api_response({
            "response": "400",
            "message": "Request body is required"
        }, 400)
    
    # Validate required fields
    required_fields = ['user_input']
    missing_fields = [field for field in required_fields if field not in data]
    if missing_fields:
        return create_api_response({
            "response": "400",
            "message": f"Missing required fields: {', '.join(missing_fields)}"
        }, 400)
    
    # Extract parameters with defaults
    system_prompt = data.get('system_prompt', 'You are a helpful AI assistant')
    user_input = data.get('user_input', '')
    max_completion_tokens = int(data.get('max_completion_tokens', 100000))
    reasoning_effort = data.get('reasoning_effort', 'medium')
    json_output = data.get('json_output', False)
    context_id = data.get('context_id')
    
    # Validate and clean context_id - treat empty strings as None
    if context_id and isinstance(context_id, str):
        context_id = context_id.strip()
        if not context_id:  # Empty string after stripping
            context_id = None
    else:
        context_id = None
    
    # Validate max_completion_tokens range
    if not (1 <= max_completion_tokens <= 120000):
        return create_api_response({
            "response": "400",
            "message": "max_completion_tokens must be between 1 and 120000"
        }, 400)
    
    # Validate reasoning_effort
    valid_reasoning_efforts = ["high", "medium", "low"]
    if reasoning_effort not in valid_reasoning_efforts:
        return create_api_response({
            "response": "400",
            "message": f"reasoning_effort must be one of: {', '.join(valid_reasoning_efforts)}"
        }, 400)
    
    try:
        # Log API usage
        logger.info(f"O3-Mini API called by user: {user_id}")
        
        # Apply context if provided (same as gpt-4o implementation)
        if context_id:
            from apis.llm.context_integration import apply_context_to_system_prompt
            enhanced_system_prompt, error = apply_context_to_system_prompt(system_prompt, context_id, g.user_id)
            if error:
                logger.warning(f"Error applying context {context_id}: {error}")
                # Continue with original system prompt but log the issue
                enhanced_system_prompt = system_prompt
        else:
            enhanced_system_prompt = system_prompt
        
        # Use the service function with enhanced system prompt
        service_response = o3_mini_service(
            system_prompt=enhanced_system_prompt,  # Use enhanced prompt with context
            user_input=user_input,
            max_completion_tokens=max_completion_tokens,
            reasoning_effort=reasoning_effort,
            json_output=json_output
        )
        
        if not service_response["success"]:
            logger.error(f"O3-Mini API error: {service_response['error']}")
            status_code = 500 if not str(service_response["error"]).startswith("4") else 400
            return create_api_response({
                "response": str(status_code),
                "message": service_response["error"]
            }, status_code)
        
        # Prepare successful response with user details and context information
        return create_api_response({
            "response": "200",
            "message": service_response["result"],
            "user_id": user_details["id"],
            "user_name": user_details["user_name"],
            "user_email": user_details["user_email"],
            "model": service_response["model"],
            "client_used": service_response["client_used"],
            "context_used": context_id if context_id else "none",
            "prompt_tokens": service_response["prompt_tokens"],
            "completion_tokens": service_response["completion_tokens"],
            "total_tokens": service_response["total_tokens"],
            "cached_tokens": service_response.get("cached_tokens", 0)
        }, 200)
        
    except Exception as e:
        logger.error(f"O3-Mini API error: {str(e)}")
        status_code = 500 if not str(e).startswith("4") else 400
        return create_api_response({
            "response": str(status_code),
            "message": str(e)
        }, status_code)

def register_llm_o3_mini(app):
    """Register routes with the Flask app"""
    from apis.utils.logMiddleware import api_logger
    from apis.utils.balanceMiddleware import check_balance
    from apis.utils.usageMiddleware import track_usage
    from apis.utils.rbacMiddleware import check_endpoint_access    

    app.route('/llm/o3-mini', methods=['POST'])(track_usage(api_logger(check_endpoint_access(check_balance(o3_mini_route)))))