from flask import jsonify, request, g, make_response
from apis.utils.tokenService import TokenService
from apis.utils.databaseService import DatabaseService
import logging
import pytz
from datetime import datetime
from apis.utils.llmServices import mistral_nemo_service  # Import the service function

# CONFIGURE LOGGING
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

from apis.utils.config import create_api_response

def mistral_nemo_route():
    """
    Consumes 2 AI credits per call
    
    Mistral Nemo LLM model for text generation and general task completion.
    
    ---
    tags:
      - LLM
    parameters:
      - name: X-Token
        in: header
        type: string
        required: true
        description: Authentication token
      - name: X-Correlation-ID
        in: header
        type: string
        required: false
        description: Unique identifier for tracking requests across multiple systems
      - name: body
        in: body
        required: true
        schema:
          type: object
          required:
            - user_input
          properties:
            system_prompt:
              type: string
              description: System prompt to control model behavior
              default: "You are a helpful AI assistant"
            user_input:
              type: string
              description: Text for the model to process
            temperature:
              type: number
              format: float
              minimum: 0
              maximum: 1
              default: 0.7
              description: Controls randomness (0=focused, 1=creative)
            max_tokens:
              type: integer
              default: 2048
              description: Maximum number of tokens to generate
            top_p:
              type: number
              format: float
              minimum: 0.1
              maximum: 1
              default: 0.1
              description: Controls diversity via nucleus sampling
            presence_penalty:
              type: number
              format: float
              minimum: -2
              maximum: 2
              default: 0
              description: Penalizes new tokens based on whether they appear in the text so far
            frequency_penalty:
              type: number
              format: float
              minimum: -2
              maximum: 2
              default: 0
              description: Penalizes new tokens based on their existing frequency in the text so far
            context_id:
              type: string
              description: ID of a context file to use as an enhanced system prompt (optional)
    produces:
      - application/json
    responses:
      200:
        description: Successful model response
        schema:
          type: object
          properties:
            response:
              type: string
              example: "200"
            message:
              type: string
              example: "I'll help you with that question. Based on the information provided..."
            user_id:
              type: string
              example: "user123"
            user_name:
              type: string
              example: "John Doe"
            user_email:
              type: string
              example: "john.doe@example.com"
            model:
              type: string
              example: "mistral-nemo"
            client_used:
              type: string
              example: "primary"
              description: Which client endpoint was used (primary, secondary)
            prompt_tokens:
              type: integer
              example: 125
              description: Number of tokens pass in the prompt
            completion_tokens:
              type: integer
              example: 84
              description: Number of tokens generated by the llm
            total_tokens:
              type: integer
              example: 209
              description: Total number of tokens used
            cached_tokens:
              type: integer
              example: 0
              description: Number of cached tokens (if supported by model)  
            context_used:
              type: string
              example: "ctx-123"
              description: ID of the context file that was used (if any)
      400:
        description: Bad request
        schema:
          type: object
          properties:
            response:
              type: string
              example: "400"
            message:
              type: string
              example: "Missing required fields: user_input"
      401:
        description: Authentication error
        schema:
          type: object
          properties:
            error:
              type: string
              example: "Authentication Error"
            message:
              type: string
              example: "Token has expired"
      500:
        description: Server error
        schema:
          type: object
          properties:
            response:
              type: string
              example: "500"
            message:
              type: string
              example: "Internal server error occurred during API request"
    """
    # Get token from X-Token header
    token = request.headers.get('X-Token')
    if not token:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Missing X-Token header"
        }, 401)
    
    # Validate token from database
    token_details = DatabaseService.get_token_details_by_value(token)
    if not token_details:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Invalid token - not found in database"
        }, 401)
    
    # Store token ID and user ID in g for logging and balance check
    g.token_id = token_details["id"]
    g.user_id = token_details["user_id"]  # This is critical for the balance middleware
    
    # Check if token is expired
    now = datetime.now(pytz.UTC)
    expiration_time = token_details["token_expiration_time"]
    
    # Ensure expiration_time is timezone-aware
    if expiration_time.tzinfo is None:
        johannesburg_tz = pytz.timezone('Africa/Johannesburg')
        expiration_time = johannesburg_tz.localize(expiration_time)
        
    if now > expiration_time:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Token has expired"
        }, 401)
    
    # Validate token with Microsoft Graph
    is_valid = TokenService.validate_token(token)
    if not is_valid:
        return create_api_response({
            "error": "Authentication Error",
            "message": "Token is no longer valid with provider"
        }, 401)
        
    # Get user details
    user_id = token_details["user_id"]
    user_details = DatabaseService.get_user_by_id(user_id)
    if not user_details:
        return create_api_response({
            "error": "Authentication Error",
            "message": "User associated with token not found"
        }, 401)
    
    # Get request data
    data = request.get_json()
    if not data:
        return create_api_response({
            "response": "400",
            "message": "Request body is required"
        }, 400)
    
    # Validate required fields
    required_fields = ['user_input']
    missing_fields = [field for field in required_fields if field not in data]
    if missing_fields:
        return create_api_response({
            "response": "400",
            "message": f"Missing required fields: {', '.join(missing_fields)}"
        }, 400)
    
    # Extract parameters with defaults
    system_prompt = data.get('system_prompt', 'You are a helpful AI assistant')
    user_input = data.get('user_input', '')
    temperature = float(data.get('temperature', 0.7))
    max_tokens = int(data.get('max_tokens', 2048))
    top_p = float(data.get('top_p', 0.1))
    presence_penalty = float(data.get('presence_penalty', 0))
    frequency_penalty = float(data.get('frequency_penalty', 0))
    context_id = data.get('context_id')  # New parameter for context_id
    
    # Validate and clean context_id - treat empty strings as None
    if context_id and isinstance(context_id, str):
        context_id = context_id.strip()
        if not context_id:  # Empty string after stripping
            context_id = None
    else:
        context_id = None
    
    # Validate temperature range
    if not (0 <= temperature <= 1):
        return create_api_response({
            "response": "400",
            "message": "Temperature must be between 0 and 1"
        }, 400)
    
    # Validate top_p range
    if not (0 <= top_p <= 1):
        return create_api_response({
            "response": "400",
            "message": "top_p must be between 0 and 1"
        }, 400)
    
    # Validate presence_penalty range
    if not (-2 <= presence_penalty <= 2):
        return create_api_response({
            "response": "400",
            "message": "presence_penalty must be between -2 and 2"
        }, 400)
    
    # Validate frequency_penalty range
    if not (-2 <= frequency_penalty <= 2):
        return create_api_response({
            "response": "400",
            "message": "frequency_penalty must be between -2 and 2"
        }, 400)
    
    try:
        # Log API usage
        logger.info(f"Mistral Nemo API called by user: {user_id}")
        
        # Apply context if provided (now properly validated)
        if context_id:
            from apis.llm.context_integration import apply_context_to_system_prompt
            enhanced_system_prompt, error = apply_context_to_system_prompt(system_prompt, context_id, g.user_id)
            if error:
                logger.warning(f"Error applying context {context_id}: {error}")
                # Continue with original system prompt but log the issue
                enhanced_system_prompt = system_prompt
        else:
            enhanced_system_prompt = system_prompt
        
        # Use the service function instead of direct API call
        service_response = mistral_nemo_service(
            system_prompt=enhanced_system_prompt,  # Use enhanced prompt with context
            user_input=user_input,
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=top_p,
            presence_penalty=presence_penalty,
            frequency_penalty=frequency_penalty
        )
        
        if not service_response["success"]:
            logger.error(f"Mistral Nemo API error: {service_response['error']}")
            status_code = 500 if not str(service_response["error"]).startswith("4") else 400
            return create_api_response({
                "response": str(status_code),
                "message": service_response["error"]
            }, status_code)
        
        # Prepare successful response with user details - consistent structure
        response_data = {
            "response": "200",
            "message": service_response["result"],
            "user_id": user_details["id"],
            "user_name": user_details["user_name"],
            "user_email": user_details["user_email"],
            "model": service_response["model"],
            "client_used": service_response.get("client_used", "unknown"),
            "prompt_tokens": service_response["prompt_tokens"],
            "completion_tokens": service_response["completion_tokens"],
            "total_tokens": service_response["total_tokens"],
            "cached_tokens": service_response.get("cached_tokens", 0)
        }
        
        # Always include context usage info - show "none" if no context was used
        response_data["context_used"] = context_id if context_id else "none"
        
        return create_api_response(response_data, 200)
        
    except Exception as e:
        logger.error(f"Mistral Nemo API error: {str(e)}")
        status_code = 500 if not str(e).startswith("4") else 400
        return create_api_response({
            "response": str(status_code),
            "message": str(e)
        }, status_code)

def register_llm_mistral_nemo(app):
    """Register routes with the Flask app"""
    from apis.utils.logMiddleware import api_logger
    from apis.utils.balanceMiddleware import check_balance
    from apis.utils.usageMiddleware import track_usage
    from apis.utils.rbacMiddleware import check_endpoint_access
    
    app.route('/llm/mistral-nemo', methods=['POST'])(track_usage(api_logger(check_endpoint_access(check_balance(mistral_nemo_route)))))