SELECT [id]
      ,[endpoint_id]
      ,[user_id]
      ,[timestamp]
      ,[request_method]
      ,[request_headers]
      ,[request_body]
      ,[response_body]
      ,[response_status]
      ,[response_time_ms]
      ,[user_agent]
      ,[ip_address]
      ,[token_id]
      ,[error_message]
  FROM [AIAPISDEV].[dbo].[api_logs]
  ORDER BY timestamp DESC;
