SELECT [id]
      ,[user_name]
      ,[user_email]
      ,[common_name]
      ,[api_key]
      ,[scope]
      ,[active]
      ,[created_at]
      ,[modified_at]
      ,[comment]
      ,[company]
      ,[department]
  FROM [AIAPISDEV].[dbo].[users]
  ORDER BY created_at DESC;
