
# MS ENTRA APP DETAILS
export ENTRA_APP_TENANT_ID=""
export ENTRA_APP_CLIENT_ID=""
export ENTRA_APP_CLIENT_SECRET=""

# DATABASE DETAILS
export DB_DRIVER=""
export DB_SERVER=""
export DB_NAME=""
export DB_USER=""
export DB_PASSWORD=""
